#!/usr/bin/env bash
# Webhook Receiver — installer.
# Asks for webhook domain + DB credentials, generates admin password,
# writes .env + initializes config.json in the docker volume, then starts the stack.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED=$'\033[0;31m'; GRN=$'\033[0;32m'; YLW=$'\033[0;33m'; CYN=$'\033[0;36m'; NC=$'\033[0m'

err()  { printf '%s✗%s %s\n' "$RED" "$NC" "$*" >&2; }
ok()   { printf '%s✓%s %s\n' "$GRN" "$NC" "$*"; }
warn() { printf '%s!%s %s\n' "$YLW" "$NC" "$*"; }
info() { printf '%s»%s %s\n' "$CYN" "$NC" "$*"; }

ask() {
    local prompt="$1" default="${2:-}" var
    if [[ -n "$default" ]]; then
        read -rp "$prompt [$default]: " var
        printf '%s' "${var:-$default}"
    else
        while :; do
            read -rp "$prompt: " var
            if [[ -n "$var" ]]; then printf '%s' "$var"; return; fi
            err "Значение не может быть пустым"
        done
    fi
}

ask_secret() {
    local prompt="$1" var
    while :; do
        read -rsp "$prompt: " var; echo >&2
        if [[ -n "$var" ]]; then printf '%s' "$var"; return; fi
        err "Значение не может быть пустым"
    done
}

confirm() {
    local prompt="$1" default="${2:-N}" yn
    read -rp "$prompt [${default}]: " yn
    yn="${yn:-$default}"
    [[ "${yn,,}" == "y" || "${yn,,}" == "yes" ]]
}

# ─── 1. Pre-flight ───────────────────────────────────────────────────────────
info "Проверка окружения"
command -v docker >/dev/null 2>&1 || { err "Не найден 'docker'"; exit 1; }
docker compose version >/dev/null 2>&1 || { err "Не найден 'docker compose' (v2)"; exit 1; }
ok "docker и compose найдены"

for net in proxy db-shared; do
    if docker network inspect "$net" >/dev/null 2>&1; then
        ok "Сеть '$net' существует"
    else
        if [[ "$net" == "db-shared" ]]; then
            warn "Сеть 'db-shared' не существует"
            if confirm "Создать?" "Y"; then
                docker network create db-shared >/dev/null
                ok "Сеть db-shared создана"
            else
                err "Без сети db-shared стек не запустится"; exit 1
            fi
        else
            err "Сеть 'proxy' не существует — это сеть Traefik. Поднимите Traefik-стек до установки."
            exit 1
        fi
    fi
done

# ─── 2. .env check ───────────────────────────────────────────────────────────
if [[ -f .env ]]; then
    warn ".env уже существует"
    if ! confirm "Перезаписать (текущий ADMIN_SECRET будет утерян)?" "N"; then
        info "Отмена установки"; exit 0
    fi
fi

# ─── 3. Inputs ───────────────────────────────────────────────────────────────
echo
info "Параметры установки"

while :; do
    WEBHOOK_DOMAIN=$(ask "  Домен для вебхуков (например, webhook.example.com)")
    if [[ "$WEBHOOK_DOMAIN" =~ ^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$ ]]; then break; fi
    err "Невалидный домен"
done

echo
info "Подключение к MySQL/MariaDB (база WordPress)"
DB_HOST=$(ask "  host" "mariadb")
while :; do
    DB_PORT=$(ask "  port" "3306")
    if [[ "$DB_PORT" =~ ^[0-9]+$ ]] && (( DB_PORT >= 1 && DB_PORT <= 65535 )); then break; fi
    err "Порт должен быть 1-65535"
done
DB_USER=$(ask "  user")
DB_PASS=$(ask_secret "  password")
DB_NAME=$(ask "  database")
DB_PREFIX=$(ask "  table prefix" "wp_")

echo
info "Файл .env с SMTP-настройками (используется worker'ом для писем)"
SMTP_ENV_FILE=$(ask "  путь (Enter — оставить дефолт; путь может не существовать, он опционален)" "/home/igor/site/.env")
if [[ ! -f "$SMTP_ENV_FILE" ]]; then
    warn "Файл $SMTP_ENV_FILE не найден — worker запустится без SMTP, email-уведомления работать не будут"
fi

# ─── 4. Generate admin password ──────────────────────────────────────────────
if command -v openssl >/dev/null 2>&1; then
    ADMIN_SECRET=$(openssl rand -base64 32 | tr -d '/+=\n' | head -c 24)
fi
if [[ -z "${ADMIN_SECRET:-}" || ${#ADMIN_SECRET} -lt 24 ]]; then
    ADMIN_SECRET=$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)
fi

# ─── 5. Write .env ───────────────────────────────────────────────────────────
umask 077
cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
ADMIN_SECRET=$ADMIN_SECRET
WEBHOOK_DOMAIN=$WEBHOOK_DOMAIN
SMTP_ENV_FILE=$SMTP_ENV_FILE
TZ=UTC
EOF
chmod 600 .env
ok ".env создан (chmod 600)"

# ─── 6. Build image ──────────────────────────────────────────────────────────
echo
info "Сборка образа (1-2 минуты)"
docker compose build
ok "Образ собран"

# ─── 7. Init config.json in volume ───────────────────────────────────────────
echo
info "Запись настроек БД в config.json"

# Pass DB credentials via a temporary --env-file (mode 600) to avoid exposing
# the password on the command line (visible in `ps -ef` / /proc/<pid>/cmdline).
TMP_ENV=$(mktemp -p . .db.env.XXXXXX)
chmod 600 "$TMP_ENV"
trap 'shred -u "$TMP_ENV" 2>/dev/null || rm -f "$TMP_ENV"' EXIT
{
    printf '_DB_HOST=%s\n'   "$DB_HOST"
    printf '_DB_PORT=%s\n'   "$DB_PORT"
    printf '_DB_USER=%s\n'   "$DB_USER"
    printf '_DB_PASS=%s\n'   "$DB_PASS"
    printf '_DB_NAME=%s\n'   "$DB_NAME"
    printf '_DB_PREFIX=%s\n' "$DB_PREFIX"
} > "$TMP_ENV"

docker compose run --rm --no-deps \
    --env-file "$TMP_ENV" \
    --entrypoint python \
    app-admin -c "
import os
from app.config import load, save
cfg = load()
cfg['db'] = {
    'host': os.environ['_DB_HOST'],
    'port': int(os.environ['_DB_PORT']),
    'user': os.environ['_DB_USER'],
    'password': os.environ['_DB_PASS'],
    'database': os.environ['_DB_NAME'],
    'table_prefix': os.environ['_DB_PREFIX'],
}
save(cfg)
print('config.json initialized at', os.environ.get('CONFIG_PATH', '/data/config.json'))
"
ok "Настройки БД сохранены"

# ─── 8. Start ────────────────────────────────────────────────────────────────
echo
info "Запуск стека"
docker compose up -d

sleep 4
echo
docker compose ps

# ─── 9. Summary ──────────────────────────────────────────────────────────────
HOSTNAME_HINT=$(hostname -f 2>/dev/null || echo your-server)
cat <<EOF

═══════════════════════════════════════════════════════════════════
  ${GRN}УСТАНОВКА ЗАВЕРШЕНА${NC}
═══════════════════════════════════════════════════════════════════

  ${YLW}Пароль админки${NC} (сохрани сейчас, повторно не покажется):

    ${GRN}${ADMIN_SECRET}${NC}

  Домен вебхуков:  ${WEBHOOK_DOMAIN}
  SMTP env file:   ${SMTP_ENV_FILE}

  ${CYN}Доступ к админке${NC} (через SSH-туннель):
    ssh -L 8098:localhost:8098 user@${HOSTNAME_HINT}
    → http://localhost:8098

  ${CYN}Дальнейшие шаги:${NC}
    1. Если миграция БД ещё не применена:
         mysql -u root -p ${DB_NAME} < migration.sql
    2. Открой админку, добавь CPA-сети.
    3. Скопируй сгенерированный webhook URL и вставь в настройки CPA-сети.

═══════════════════════════════════════════════════════════════════
EOF
